---
- name: install Adafruit DHT library
  command: "python setup.py install {{ greenpithumb_adafruit_dht_extra_args }}"
  args:
    chdir: "{{ __greenpithumb_adafruit_dht_tmp_path }}"

- name: reload systemd configs
  systemd:
    daemon_reload: yes
    name: greenpithumb-backend

- name: restart greenpithumb-backend
  service:
    name: greenpithumb-backend
    state: restarted

- name: restart greenpithumb-frontend
  service:
    name: greenpithumb-frontend
    state: restarted

- name: set greenpithumb backend file permissions
  file:
    path: "{{ greenpithumb_backend_path }}"
    owner: "{{ greenpithumb_backend_user }}"
    group: "{{ greenpithumb_backend_group }}"
    recurse: yes
    state: directory

- name: set greenpithumb frontend file permissions
  file:
    path: "{{ greenpithumb_frontend_path }}"
    owner: "{{ greenpithumb_frontend_user }}"
    group: "{{ greenpithumb_frontend_group }}"
    recurse: yes
    state: directory
