---
- name: install Adafruit DHT library
  command: "python setup.py install {{ greenpithumb_adafruit_dht_extra_args }}"
  args:
    chdir: "{{ __greenpithumb_adafruit_dht_tmp_path }}"

- name: reload greenpithumb-backend
  service:
    name: greenpithumb-backend
    state: reloaded

- name: restart greenpithumb-backend
  service:
    name: greenpithumb-backend
    state: restarted

- name: reload greenpithumb-frontend
  service:
    name: greenpithumb-frontend
    state: reloaded

- name: restart greenpithumb-frontend
  service:
    name: greenpithumb-frontend
    state: restarted

- name: set greenpithumb backend file permissions
  file:
    path: "{{ greenpithumb_backend_path }}"
    owner: "{{ greenpithumb_backend_user }}"
    group: "{{ greenpithumb_backend_group }}"
    recurse: yes
    state: directory

- name: set greenpithumb frontend file permissions
  file:
    path: "{{ greenpithumb_frontend_path }}"
    owner: "{{ greenpithumb_frontend_user }}"
    group: "{{ greenpithumb_frontend_group }}"
    recurse: yes
    state: directory

- name: set greenpithumb frontend static file permissions
  file:
    path: "{{ greenpithumb_frontend_static_root }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    recurse: yes
    state: directory

- name: install greenpithumb frontend static dependencies
  npm:
    path: "{{ greenpithumb_frontend_static_root }}"
    production: "{{ greenpithumb_npm_production_mode }}"
  become_user: "{{ nginx_user }}"
